### ISSUE TITLE
How to custom correlation-id in rxStompRPC case

### ISSUE THREAD

**Issue by sundogya** [stomp-js/rx-stomp#129]
When i use stomp-js for rpc , i cant custom my correlation-id ( although i try to set it in headers ,it just dont work).Any methods to resolve this ?

**Comment by kum-deepak** [comment]
Currently it is not possible to override. It will need a code change at rxStompRPC (https://github.com/stomp-js/rx-stomp/blob/master/src/rx-stomp-rpc.ts#L64) to not generate a new id if a correlation-id header is in the passed argument.

I am just curious why do you need a custom correlation-id?

**Comment by kum-deepak** [comment]
Released version 0.3.3, please update and try.

**Comment by sundogya** [comment]
Thank you very much！------------------ 原始邮件 ------------------
发件人: "Deepak Kumar"<notifications@github.com>
发送时间: 2019年8月22日(星期四) 中午12:55
收件人: "stomp-js/rx-stomp"<rx-stomp@noreply.github.com>;
抄送: "Jinbao Gao"<2267179139@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [stomp-js/rx-stomp] How to custom correlation-id in rxStompRPCcase (#129)



Released version 0.3.3, please update and try.
 
&mdash;
