### ISSUE TITLE
Advice: Testing subscriptions in multiple browser tabs / sessions

### ISSUE THREAD

**Issue by JamieKalloe** [stomp-js/rx-stomp#166]
Hi there,

I'm looking for some advice / best practises regarding the testing of RxStomp subscriptions using multiple browser sessions.

Right now I'm using the STOMP plugin for RabbitMQ, and I'm using RxStomp for the client side.
Whenever I open a new browser tab (to simulate another subscriber) the subscription id will still be 0.

Example:
`>>> SUBSCRIBE
ack:auto
id:sub-0
destination:event.ronde.1.registered-jury`

This behaviour results in just one subscriber (of sub-0) receiving the message.
What I want to test is simulating multiple subscribers, using multiple browser tabs, so that every tab will be assigned an unique sub-id and that all browser tabs will receive the message.

Some guidance on this problem would be very much appreciated!

Thanks and happy holidays!

Jamie

**Comment by kum-deepak** [comment]
Different browsers tabs create their own connection to the broker. They do not interfere with each other. The subscription id are required to be unique within a connection, so, that being same across multiple tabs is not an issue.

I routinely test samples using multiple tabs. There is a rx-chat sample at https://github.com/stomp-js/samples/#rx-stomp. Running this in multiple tabs should work as expected. See if this sample helps you.

**Comment by JamieKalloe** [comment]
I see, thank you for your help!

**Comment by JamieKalloe** [comment]
Unfortunately this problem still persists, whenever I subscribe (also in different tabs) the `sub-id` will always be 0.

I'm using rabbitmq, with the rabbitmq stomp plugin. On my queue it does say 2 consumers, however in the client the subscriber id, for different sessions, are always 0.
This results in just one of the tabs receiving a message through the subscription.

This is my implementation of the RxStompService:
`public subscribe(rondeId: number, callBack: (newJury: Jury) => void): Subscription {
        return this.stompService
            .watch(`event.ronde.${rondeId}.registered-jury`)
            .subscribe((receivedMessage: Message) => {
                const connectedJury = JSON.parse(receivedMessage.body) as Jury;

                callBack(connectedJury);
            });
    }`

In call this method in my code like this:
`this.newJurySubscription = this.juryService.subscribe(this.ronde.id, (newJury: Jury) => this.onJuryRegistered(newJury));`

Then the callback method is called through the subscribe method:
`  private onJuryRegistered(newJury: Jury): void {
    this.juries.push(newJury); //jury array
  }`

In the ngOnDestroy method the I call the unsubscribe method for the subscription.
Both tabs will **always** have a **sub-id of 0**, as shown in the console logs:
`>>> SUBSCRIBE
ack:auto
id:sub-0
destination:event.ronde.1.registered-jury`

However just **one** of the two tabs gets the actual message:
`<<< MESSAGE
content-length:35
content-type:application/json
content-encoding:UTF-8
persistent:true
priority:0
__TypeId__:nl.contrivance.magenta.juryservice.model.Jury
redelivered:false
message-id:T_sub-0@@session-qym7i010-yYt7xZewYZJOA@@1
destination:/queue/event.ronde.1.registered-jury
subscription:sub-0
content-length:35`

I really have no clue why this code doesn't seem to work.
As you, @kum-deepak , have stated before, even through multiple tabs it should be standard behaviour.

I hope you could help me with this issue.

**Comment by JamieKalloe** [comment]
The problem has been resolved.
Turns out it wasn't the stomp client at all, it was a back-end issue.

I was subscribing directly to a queue (like 'queue.name') instead of a topic (like '/topic/topic.name').
Therefore the RxStompService wouldn't create a queue for every subscriber, therefore only delivering it to just one subscriber (since each subscriber became a competitive subcriber for the messages of one queue).

Thanks you the support though, it has been helpful for finding the answer.
