### ISSUE TITLE
Not possible to set headers in before connect

### ISSUE THREAD

**Issue by emanuelefricano93** [stomp-js/rx-stomp#204]
Please see FAQs at https://stomp-js.github.io/faqs/2019/05/20/faqs.html before reporting.
![image](https://user-images.githubusercontent.com/26500344/78413480-dc442400-7617-11ea-908b-de468727f2df.png)

![image](https://user-images.githubusercontent.com/26500344/78413495-ea924000-7617-11ea-88de-7a9ff9c041b2.png)

Hello, I have tried locally, with this small fix to use the RxStompConfig and the beforeConnect method in order to set my headers coming from an async request, then resolve the promise and successfully connect my client via web socket.

Is there some reason about the signature of the beforeConnect is () : void | Promise<void>
without any reference to the stompclient ? or at least the headers?
This could help in the configuration.

Anyway, we were able to connect using another strategy like indicated by you, instantiated the  RxStompConfig and using rxStompServiceFactory.

**Comment by kum-deepak** [comment]
See #205.

**Comment by kum-deepak** [comment]
Released 0.3.5 with a fix. `beforeConnect` will receive `client` as parameter.

**Comment by emanuelefricano93** [comment]
Thanks a lot kum-deepak!

**Comment by Donkijote** [comment]
Hi, I follow the code you did @emanuelefricano93 but for some reason the it throws URL undefined error, then I changed to the tutorial written by @kum-deepak and everything works fine, but the headers are not present in the requests, so I got a http 403 forbiden response from the backend, can any one give a hand? thanks for your time

**Comment by kum-deepak** [comment]
@Donkijote please attach your configuration, the before connect function, and console output.

**Comment by Donkijote** [comment]
Using @emanuelefricano93 approach

stopmConfig

![image](https://user-images.githubusercontent.com/7980621/104027748-991a7100-51a6-11eb-9ed9-1324be19a64e.png)


Console Error:
![image](https://user-images.githubusercontent.com/7980621/104027444-29a48180-51a6-11eb-9e5d-ad6c54dad82a.png)


Using tutorial config:

![image](https://user-images.githubusercontent.com/7980621/104027815-b0f1f500-51a6-11eb-8f7a-df4722400503.png)

in this config I noticed that the beforeConnect function is being triggered but the connectHeaders are not being added

Console Error:

![image](https://user-images.githubusercontent.com/7980621/104027966-e696de00-51a6-11eb-885e-357310ea00e7.png)


Extra configuration with the tutorial config:

service.ts:

![image](https://user-images.githubusercontent.com/7980621/104028116-1a720380-51a7-11eb-8819-a4be832db44f.png)


if I add this to the service in console I got this:

![image](https://user-images.githubusercontent.com/7980621/104028170-2f4e9700-51a7-11eb-9f8d-ecdcac3b711c.png)

Now the connect headers appeared but still the headers are not being sent 

![image](https://user-images.githubusercontent.com/7980621/104028257-44c3c100-51a7-11eb-8546-9efd01d7959f.png)

And without the headers I'm getting Http 403 error

**Comment by kum-deepak** [comment]
From the information you have shared, it appears to be some other issue to start with:

- During Websocket connection (wss://...), it first connects as https. Once https connection is established, the connectHeaders are sent as part of STOMP CONNECT frame.
- In your case, https connection is not getting established.

Please check your broker configuration for the following:

- Does the broker support Websocket (wss:// protocol) or does it support SockJS? In case it supports SockJS the configuration would be different.
- How does it expect the Authentication information - as part of HTTP headers or as part of CONNECT Frame? This library does not support Authentication information as part of HTTP headers.

See https://stomp-js.github.io/faqs/faqs.html#p-can-i-use-token-based-authentication-with-these-libraries-p as well.

**Comment by Donkijote** [comment]
> From the information you have shared, it appears to be some other issue to start with:
> 
> * During Websocket connection (wss://...), it first connects as https. Once https connection is established, the connectHeaders are sent as part of STOMP CONNECT frame.
> * In your case, https connection is not getting established.
> 
> Please check your broker configuration for the following:
> 
> * Does the broker support Websocket (wss:// protocol) or does it support SockJS? In case it supports SockJS the configuration would be different.
> * How does it expect the Authentication information - as part of HTTP headers or as part of CONNECT Frame? This library does not support Authentication information as part of HTTP headers.
> 
> See https://stomp-js.github.io/faqs/faqs.html#p-can-i-use-token-based-authentication-with-these-libraries-p as well.

We need to pass the Authorization by HTTP due to the api gateway expects that header with JWT token to validate the user.

I'll check the others points your sharing, thanks very much

**Comment by HernandezWilly** [comment]
Tengo el mismo problema no envia las cabeceras, como han resulto el problema,
utilizo en el backend spring security 
![Captura de Pantalla 2021-05-17 a la(s) 14 10 12](https://user-images.githubusercontent.com/84345103/118543201-99f57d80-b719-11eb-8a27-b0e468522738.png)
![Captura de Pantalla 2021-05-17 a la(s) 14 11 05](https://user-images.githubusercontent.com/84345103/118543307-b8f40f80-b719-11eb-8885-5a1645950af9.png)

**Comment by Luqheltod** [comment]
Is there any solution for this? I have the same issue

**Comment by HdzWilly** [comment]
Hi, in config class just use the method sameDisabled(), I already have security through spring security and the header is not necessa
![imagen](https://user-images.githubusercontent.com/84345103/134726899-35cc5daa-4e75-439a-8138-fd0ab
![imagen](https://user-images.githubusercontent.com/84345103/134727003-c800392b-cc5f-4a48-b1b4-3c278ec0e71d.png)
2a908e5.png)
ry

**Comment by danlz** [comment]
'connectHeaders' is not the solution in this case, because these headers are added to the CONNECT message sent over the web socket.
What you really want is to add the "Authorization" header to the first GET request (so called Upgrade request) sent to server.
This is unfortunately not possible with the WebSocket Javascript object.

Alternative solution (but not recommended, because of security reasons):
Pass the token in "access_token" query string parameter, ie ws://server/ws?access_token=12345
SpringBoot will automatically pick up this token.

**Comment by akmal2409** [comment]
For anyone using it along Spring Websocket Integration and who had defined the custom channel interceptor to introspect the CONNECT frame and validate the credentials, disabled .withSockJs() on StompEndpointRegistry instance and it will start to work. Not sure what is the problem.

**Comment by davideas** [comment]
So, I'm in the same issue of setting the Auth header for the connection, but the package departs without this header from the Browser.
I am falling back to use the token as parameter, but i don't really get why other headers are sent and we cannot set ours.
I tried the `beforeConnect `but it doesn't work.

``` typescrit
@Injectable()
export class WebSocketService extends RxStomp {
    activate() {
        rxStompConfig.beforeConnect = (stompClient: any): Promise<void> => {
            return new Promise<void>((resolve, reject) => {
                OpenIdConnect.getAuthorizationHeaders('/kiddymob/api/v4/something', (headers) => {
                    stompClient.connectHeaders = headers; // This is json onject: "{ Authorization: bearer xxxxx }"
                    resolve();
                });
            });
        };
        super.configure(rxStompConfig);
        super.activate();
    }
}
```
Need help, thank you.

**Comment by davideas** [comment]
Ok, I have found in the other project (stomp-js) the final answer.
I report it here, so all can refer and abandon this solution which will never work: it's blocked by the browsers implementation => must use the parameter.
End of the story.

https://github.com/stomp-js/stompjs/issues/322#issuecomment-766698673
