### ISSUE TITLE
Subscriptions multiplexing

### ISSUE THREAD

**Issue by antonmoiseev** [stomp-js/rx-stomp#211]
Is there something similar to RxJS [webSocket multiplexing](https://rxjs-dev.firebaseapp.com/api/webSocket/webSocket) feature (see Multiplexing section), but on the STOMP level? In other words, is it possible to call `RxStomp.watch()` multiple times with the same destination, but send only one `SUBSCRIBE` frame to the server? This can be useful when you want to subscribe to the same data in multiple places of the application.

**Comment by kum-deepak** [comment]
The Observable returned by `RxStomp.watch` is sharable, these can be subscribed multiple times. In that case internally one subscription exists. It uses https://rxjs-dev.firebaseapp.com/api/operators/share

The sample https://github.com/stomp-js/ng2-stompjs-angular7 relies on that - quite subtly though.

**Comment by antonmoiseev** [comment]
Thank you.
