### ISSUE TITLE
Expose Ecmascript module for Angular

### ISSUE THREAD

**Issue by larsvanhilten** [stomp-js/rx-stomp#224]
In Angular (10) I get the following warning:

> WARNING in [angular-service] depends on '@stomp/rx-stomp'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

I tried using [ng2-stompjs](https://github.com/stomp-js/ng2-stompjs), but, because it depends on this package, it has the same issue/warning.

Is it possible to expose an ES module, like Lodash does: https://www.npmjs.com/package/lodash-es ?

**Comment by kum-deepak** [comment]
Let me have a look. The underlying code is in Typescript, so, it should be possible to generate ES6 (or probably ES2017) modules as alternate output.

**Comment by kum-deepak** [comment]
I have created a branch `esm5` with some packaging changes. This should work with Angular. Please try installing from this branch:

```bash
$ npm i stomp-js/rx-stomp#esm5
```

Please let me know if it works. I have not tested with Angular 10.

**Comment by larsvanhilten** [comment]
I tried out the `#esm5` branch, but the warning still remains.

However, when the following is changed:

` "main": "./esm5/index.js",`
  `"module": "./esm5/index.js",`

to 

` "main": "./esm6/index.js",`
  `"module": "./esm6/index.js",`

The warning disappears.

**Comment by kum-deepak** [comment]
This is a sad situation - Earlier version of Angular fails while trying to use ES 6 version. Let me experiment a bit more.

**Comment by kum-deepak** [comment]
After making similar changes in the underlying library `@stomp/stompjs` I will release this as a beta.

**Comment by kum-deepak** [comment]
It seems to be working now. All bundlers (that rely on `import`) will use ES6 modules. nodejs (that uses commonjs `require`) will use UMD. Direct inclusion using a script tag in a page will use UMD.

Released as part of 1.0.0
