### ISSUE TITLE
How can I set unsubscribe headers?

### ISSUE THREAD

**Issue by MitoZ** [stomp-js/rx-stomp#24]
Hi, is it possible to set unsubscribe headers during calling subscribe method?
I use ngrx effects to manage my subscriptions. There is code example:
 return this._stompService.subscribe(destination)
          .pipe(
            map(ws_message => JSON.parse(ws_message.body))
            takeUntil(this.stop_subscription$),
            map((messages) => {
              return {type: someAction, payload: messages};
            });
when operator "takeUntil" is triggered stomp service does unsubsribtion but sends only "id" header, is it possible to add some other header ("destination" or other custom headers)?

**Comment by vigie** [comment]
I also need this functionality. Answers below

> Need some info:
> 
> * Which broker are you using?
RabbitMQ

> * Which headers are you intending to pass?
access-token

> * Will these header values be known while initiating subscription?
Not necessarily (value may have changes since initial subscription.

**Comment by kum-deepak** [comment]
I am reopening this issue, I will add this in the next version.

**Comment by kum-deepak** [comment]
Implemented in #254.

**Comment by kum-deepak** [comment]
Please install `@stompjs/rxstop@beta` and see https://github.com/stomp-js/rx-stomp/pull/254#issuecomment-703511385 for an example.
