### ISSUE TITLE
Issue in Increasing Incoming heartbeat interval

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [stomp-js/rx-stomp#253]
In node server even if I configure heartbeatIncoming to 20000, getting data continuously with out waiting for 20 seconds in watch.

Here is the configuration

```
rxStomp.configure({
  brokerURL: ServiceURL,
  heartbeatIncoming: 20000,
  heartbeatOutgoing: 20000,
  reconnectDelay: 200,
  debug: (msg: string): void => {
    console.log(new Date(), msg);
  },
});
```

This is my subscription:
```
return rxStomp.watch(topic).pipe(
      map((message) => {
        return JSON.parse(message.body);
      })
    );
```

**Comment by kum-deepak** [comment]
Not sure what behaviour you expected.

Heartbeat is an internal mechanism used by the broker and the client to check if the connection is still alive. It has no impact on delay in sending or receeiving messages. Messages will get delivered with least possible delay.

In case you need additional help, please attach your debug output.
