### ISSUE TITLE
Allow subHeaders to be a function, like unsubHeaders

### ISSUE THREAD

**Issue by vigie** [stomp-js/rx-stomp#298]
Imagine you are using subHeaders to pass an `access-token` - a common use case.

The problem comes in the context of automatic re-subscriptions after a disconnect.

WIthout allowing the value to be a function that can return the headers, during an automatic reconnect of the observable the client can end up sending an expired value for the token.

**Comment by vigie** [comment]
Note, ultimately fixing https://github.com/stomp-js/stompjs/issues/290 would be the cleanest solution here also, but in the meantime I think allowing a function value for the subHeader should be quick and easy...I will prep a PR if in agreement?

**Comment by kum-deepak** [comment]
Released as @stomp/rx-stomp 1.1.0 at npm.
