### ISSUE TITLE
TS1086: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by Rominet13** [stomp-js/rx-stomp#308]
Hello

First thanks for RX-STOMP !

I 'm using angular 8, and get the following check error with the new 1.1.0 version of RX-STOMP.

The error log:
"
ERROR in ../../node_modules/@stomp/rx-stomp/esm6/rx-stomp.d.ts:124:9 - error TS1086: An accessor cannot be declared in an ambient context.

124     get stompClient(): Client;
            ~~~~~~~~~~~
../../node_modules/@stomp/rx-stomp/esm6/rx-stomp.d.ts:193:9 - error TS1086: An accessor cannot be declared in an ambient context.

193     get active(): boolean;
"

I can skip it with :
  "compilerOptions": {
    "skipLibCheck": true,

Is there another solution ?  (upgrade typescript maybe ? Angular 8 is limited to "typescript": "~3.5.3")

**Comment by kum-deepak** [comment]
Current release of rx-stomp is compiled using Typescript 3.2.1. I had frozen that version to avoid this issue a while back. I have been used this library with Angula 7, 9, and 10 without this issue. However, if anyone faces the issue I know of the bypass that you are already using.

**Comment by kum-deepak** [comment]
It seems typescript dependency had gotten relaxed - maybe by - dependabot. Version 3.9.99 was getting used. As part of release 1.1.2, typescript is contained back to 3.6.x. Hopefully, it should work without the workaround now.

Leaving this issue open for reports of it working/failing.

**Comment by Rominet13** [comment]
Wonderfull it works without the workaround.
Great thank you !
