### ISSUE TITLE
ReExport IMessage, IFrame and StompHeaders from the @stomp/stompjs

### ISSUE THREAD

**Issue by akaNightmare** [stomp-js/rx-stomp#416]

**Comment by kum-deepak** [comment]
Probably additional interfaces will need exporting, like IMessageParams.

**Comment by kum-deepak** [comment]
Fixed by a7c79df39b7d6319bf3a9620888dc851b4d38995

**Comment by kum-deepak** [comment]
I just now released  @stomp/rx-stomp@2.0.0-beta1.
