### ISSUE TITLE
`deactivate` Promise never resolves

### ISSUE THREAD

**Issue by onethread** [stomp-js/rx-stomp#445]
I'm doing something like so:

`await rxStomp.deactivate();` 

But the Promise takes a long time to resolve (around 10 minutes). After I resolve, I call `activate` again, but I get the following error: `Error: Still DEACTIVATING, can not activate now`, which seems to imply that `onWebSocketClose` was not called, which should have changed the state from `DEACTIVATING` to `INACTIVE`.

I'm on version 1.1.4 of @stomp/rx-stomp.

**Comment by kum-deepak** [comment]
Thanks for the report. I will investigate it further. Please attach the complete console output.

**Comment by kum-deepak** [comment]
Looking at the code, I think I know the source of the error. Please attach the console output that will help me in confirming my conjecture,

**Comment by kum-deepak** [comment]
The deactivate logic in the next version of stompjs is getting updated. It should probably resolve this issue.

**Comment by kum-deepak** [comment]
I just now released  @stomp/rx-stomp@2.0.0-beta1. Please check if it resolves the issue.

**Comment by kum-deepak** [comment]
Released v2.0.0
