### ISSUE TITLE
connectionState$ doesn't emit value after Reconnect

### ISSUE THREAD

**Issue by bar0n-91** [stomp-js/rx-stomp#452]
Hi, i don't know if it is an issue, or it is a normal behaviour, but when then Ws lose the connection, after reconnecting, noone value is emitter from Observable connectionState$. I like to have an emitted value or maybe another RxStompState called RECONNECTED or similar.

**Comment by kum-deepak** [comment]
Please see the Enum https://stomp-js.github.io/api-docs/latest/miscellaneous/enumerations.html#RxStompState, the connectionState$ should emit 'OPEN' on every successful (re)connection. If it does not please attach your code fragment and the console log (with debug enabled).

**Comment by Joe-EdgeTech** [comment]
I know this was closed 18 days ago, but I can confirm that  `this.rxStomp.connected$` does not fire another event to anyone subscribed with the ticket I opened today: [issues/472](https://github.com/stomp-js/rx-stomp/issues/472)

In this scenario the websocket fails and tries to reconnect.  On successful reconnects I have verified that a subscription to `this.rxStomp.connected$` does not get a new event, `this.rxStomp.connectionState$` does.

**Comment by kum-deepak** [comment]
Please enable debug and attach your console output.
