### ISSUE TITLE
Use another library than angular2-uuid

### ISSUE THREAD

**Issue by rain0r** [stomp-js/rx-stomp#461]
When building my Angular 14 application, I noticed this warning:

>Warning: node_modules/@stomp/rx-stomp/esm6/rx-stomp-rpc.js depends on 'angular2-uuid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Maybe `rx-stomp` could use another library to generate UUIDs? For example `@types/uuid`.

**Comment by kum-deepak** [comment]
Committed to `develop` branch. It now uses https://github.com/uuidjs/uuid

**Comment by kum-deepak** [comment]
I just now released  @stomp/rx-stomp@2.0.0-beta1.
