### ISSUE TITLE
RXStomp, check max attempt and exponential reconnectdelay

### ISSUE THREAD

**Issue by shipra0278** [stomp-js/rx-stomp#462]
I have requirement in Angular to use websocket to get real time updates for the data grid from Active MQ.
I used Websocket to do this and need to subscribe to "topics".
 I followed https://stomp-js.github.io/guide/rx-stomp/rx-stomp-with-angular.html and created 
Configuration[Permalink](https://stomp-js.github.io/guide/rx-stomp/rx-stomp-with-angular.html#configuration)
RxStompService[Permalink](https://stomp-js.github.io/guide/rx-stomp/rx-stomp-with-angular.html#the-rxstompservice)
Factory to create and initialize RxStompService[Permalink](https://stomp-js.github.io/guide/rx-stomp/rx-stomp-with-angular.html#factory-to-create-and-initialize-rxstompservice)

Everything works fine.
**Requirment**: Now we need to check on the max attempt(4) to reconnect and reset the reconnect delay  for every attempt.

I coded in the rxStompServiceFactory. as below,
please guide me the following code is correct or is there any better way?

```typescript
export function rxStompServiceFactory() {

  let maxConnectionAttempts = 4;
  let currentTry = 0;

  const rxStomp = new RxStompService();

  myRxStompConfig.webSocketFactory = function () {
    return new SockJS('http://localhost:8080/');
  };

  myRxStompConfig.beforeConnect = () => {
    currentTry++;
 
if(currentTry> 1)
    {
      console.log(`Connection Time:  (${Date.now.toString()})
                  ReconnectDelay:   (${myRxStompConfig.reconnectDelay}) `)
        myRxStompConfig.reconnectDelay = 500 * Math.pow(2, currentTry);
        console.log(`Exponential back off - next connection attempt in ${myRxStompConfig.reconnectDelay}ms`);
    }
    if (currentTry > maxConnectionAttempts) {
      console.log(`Exceeds max attempts (${maxConnectionAttempts}), will not try to connect now`);
      // It is valid to call deactivate from beforeConnect
      rxStomp.deactivate();
    }
  };

  rxStomp.configure(myRxStompConfig);

  if(currentTry !== maxConnectionAttempts)
     rxStomp.activate();

  return rxStomp;
}
```

**Comment by kum-deepak** [comment]
Updating `myRxStompConfig` in `beforeConnect` does not alter the `rxStomp`. Please try changing

```typescript
   myRxStompConfig.reconnectDelay = 500 * Math.pow(2, currentTry);
```
to
```typescript
   rxStomp.configure({reconnectDelay: 500 * Math.pow(2, currentTry)});
```

In addition, you should reset `currentTry` on a successful connection.

**Comment by shipra0278** [comment]
Ok, thanks. 

Also, when I configure the WebSocket with URL "ws://amq.net:30007/ws", I get error. but if I if set the brokerURL with same URL "ws://amq.net:30007/ws" in config file. It was fine.

myRxStompConfig.webSocketFactory = function () {
   return new WebSocket("ws://amq.net:30007/ws");
  //return new SockJS(//'http://localhost:7777');
  };

ERROR:
Thu Aug 18 2022 08:26:06 GMT-0500 (Central Daylight Time) 'Opening Web Socket...'
rx-stomp-service-factory.ts:15 WebSocket connection to 'ws://amq.........net:30007/ws' failed: 
_config_rx_stomp_config__WEBPACK_IMPORTED_MODULE_1__.myRxStompConfig.webSocketFactory @ rx-stomp-service-factory.ts:15
_createWebSocket @ client.js:278
(anonymous) @ client.js:211
fulfilled @ client.js:4
invoke @ zone.js:372

rx-stomp.config.ts:29 Thu Aug 18 2022 08:26:06 GMT-0500 (Central Daylight Time) 'Connection closed to undefined'
rx-stomp.config.ts:29 Thu Aug 18 2022 08:26:06 GMT-0500 (Central Daylight Time) 'STOMP: scheduling reconnection in 8000ms'

Thanks
Shipra

**Comment by kum-deepak** [comment]
Glad to know it worked. I will close this issue.
