### ISSUE TITLE
receive binary data

### ISSUE THREAD

**Issue by jeme95** [stomp-js/rx-stomp#469]
I'm using RxStompRPC to send a zip file from the server (via RabbitMQ Server) to the client (browser), but I'm getting this error in the browser

`WebSocket connection to 'ws://127.0.0.1:15674/ws' failed: Could not decode a text frame as UTF-8.
`

the zip file to be transferred is encoded in ANSI (Windows-1252)

so I deduced that the WebSocket is incorrectly trying to interpret the content as UTF-8 content.

Is there a way to configure the websocket to interpret the message content as ANSI encoding or even as binary data?

**Comment by kum-deepak** [comment]
Some general suggestions:

- The text frames must be encoded as UTF-8, which is the only encoding supported by this library.
- For binary frames encoding is not checked. To set binary body use https://stomp-js.github.io/api-docs/latest/interfaces/IPublishParams.html#binaryBody

There is a test case that uses binary payload in an RPC call - https://github.com/stomp-js/rx-stomp/blob/develop/spec/unit/rpc.spec.ts#L80 - check that.

In case you need further assistance please paste the code fragment.
