### ISSUE TITLE
How to handle authentication error?

### ISSUE THREAD

**Issue by pseisam** [stomp-js/rx-stomp#473]
How can I react to authentication errors?

There is the observable webSocketErrors$ but the only info I can get from there is type = error. But I want to know what kind of error occurred like a http status code.

I don't want to do a token refresh but to logout the user on authentication error.

Any idea?

**Comment by kum-deepak** [comment]
It depends on what the broker sends. It is not part of the standards so, it will be broker specific. Please check your broker's documentation.

**Comment by pseisam** [comment]
Thanks for the reply. Unfortunately I use springs simple broker which seems to not support better error messages after reading the docs.
