### ISSUE TITLE
RxStomp client doesn`t receive heartbeat messages.

### ISSUE THREAD

**Issue by inzagher** [stomp-js/rx-stomp#488]
In my angular project i use rx-stomp client with both heartbeat parameters set. But server does not send heartbeat message. If i use stompjs, server sends heartbeat messages every 25 seconds. Is it bug, or rx-stomp client configuration settings are wrong?

RxConfig:
{
    brokerURL: 'ws://some-websocket-url',
    connectHeaders: { username: userName },
    heartbeatIncoming: 15000,
    heartbeatOutgoing: 15000,
    reconnectDelay: 30000,
    connectionTimeout: 5000
};

"@angular/core": "^14.2.5",
"@stomp/rx-stomp": "^1.2.0"

**Comment by davideas** [comment]
Hello there, it works, I'm using it.

I use Spring at server side:
``` java
@Override
public void configureMessageBroker(MessageBrokerRegistry config) {
    config.setApplicationDestinationPrefixes("/stomp");
    config.enableSimpleBroker("/topic", "/queue")
            .setHeartbeatValue(new long[]{20000, 20000}) // 20 seconds Ping-Pong
            .setTaskScheduler(new DefaultManagedTaskScheduler());
}
```
Then, in Typescript they should match.
Do some tests by modifing all values.
``` typescript
// How often to heartbeat?
// Interval in milliseconds, set to 0 to disable
heartbeatIncoming: 20000, // Typical value 0 - disabled
heartbeatOutgoing: 20000, // Typical value 20000 - every 20 seconds
```

**Comment by inzagher** [comment]
Hello. I`m using spring boot server too, without scheduler and heartbeat settings. When I set this values, typescript client sends and receives heartbeat messages. Websocket connection uses server side settings, client settings are ignored. This is exactly what I `m looking for. Thanks a lot!
