### ISSUE TITLE
Option to not auto resubscribe

### ISSUE THREAD

**Issue by kum-deepak** [stomp-js/rx-stomp#5]
Will wait for someone to actually request for this.

**Comment by raybooysen** [comment]
@kum-deepak I again, have this requirement.  Happy if I work on the PR in the same way we did the retry PR?

**Comment by kum-deepak** [comment]
Please go ahead.

In the PR, please exclude all generated files (bundle/esm5/esm6), those are taken care by the release process.

**Comment by kum-deepak** [comment]
Implemented in #254.
