### ISSUE TITLE
Feature: global hook to dynamically add headers

### ISSUE THREAD

**Issue by mstawick** [stomp-js/rx-stomp#54]
I'd like to be able to attach some headers with every message sent (be it CONNECT, SUBSCRIBE, SEND, etc). While this can be done manually for regular calls (RxStompService), it won't work with RxStompRPCService, because it only applies custom headers to SEND command. 

Would it be possible to add a hook to InjectableRxStompConfig, for example:
customHeaders: (headers: StompHeaders) => {}

that would allow for dynamic header setting for each message sent?

Cheers

**Comment by kum-deepak** [comment]
RxStompRPCService only makes publish (STOMP SEND) calls, for which headers can be passed with the rpc/stream calls. For everything else direct calls can be made to the instance of RxStompService that has been passed into the constructor of RxStompRPCService.

If you can be more specific about what you want to achieve with a code outline, I might be able to help.

I believe you have already gone through https://stomp-js.github.io/guide/rx-stomp/ng2-stompjs/2018/10/12/remote-procedure-call.html and samples at https://github.com/stomp-js/samples/.

**Comment by mstawick** [comment]
Hi,

thanks. My use case was to attach a custom header with a token to all outgoing messages. Token would change over time. I didn't want to have to add it manually for each message, hence the idea of having a global "headerProcessor" that could modify outgoing headers for every message.

If anyone is interested, it is straightforward to do by adding a function reference to config (ex. (command, headers) => {}), and then executing it in _transmit(...) of StompHandler.

But anyway, I've decided to take a different approach, so it's no longer an issue. 

Thanks for the lib, cheers.
