### ISSUE TITLE
Option to not auto retry in sending messages

### ISSUE THREAD

**Issue by kum-deepak** [stomp-js/rx-stomp#6]
Will wait for someone to actually request for this.

**Comment by raybooysen** [comment]
I'd like this.  for anything financial related, like bookTrade, placeOrder operations, we cannot retry if it fails.  We need to have the guarantee that the library won't retry to prevent financial loss.

**Comment by kum-deepak** [comment]
I will target it for next release.

**Comment by raybooysen** [comment]
Thanks!

**Comment by raybooysen** [comment]
Looking at the code, where are you auto-retrying in sending messages?  I can see if the connection is not up, it's enqueued, but if there is an error, it's bubbled.

**Comment by raybooysen** [comment]
Another small thing I noticed, since you enqueue messages, if any of the `.publish` calls fail, all messages are lost.

**Comment by raybooysen** [comment]
Actually I wonder if that's what you mean by auto-retry.  Do you mean if the connection is down, we should have an option to queue or not queue?  As opposed to retrying a message when the actual sending fails?

As another small point, if the connection comes up and there is a queue, the client tries to send them in a for loop without an error handling.  That means that if there is any error in any 1 of the messages, an unhandled error will occur leaving us in a very tricky state.

**Comment by kum-deepak** [comment]
See also #94

**Comment by kum-deepak** [comment]
Committed in `develop` branch :+1: Thanks @raybooysen
