### ISSUE TITLE
HTTP connection failure while using SocksJs 

### ISSUE THREAD

**Issue by dmcanaeko** [stomp-js/rx-stomp#67]
Is it possible to obtain more information on http connection failure? I'm using a Spring boot server with oauth2. At the moment on the client it is not possible to tell whether connection attempt fails due to network connectivity or if the oauth token is invalid. example connection factory config below.

```
rxStompConfig.webSocketFactory= function () {
    return new SockJS("http://broker.329broker.com/stomp?access_token=ecc5f3d6-ae5d-41d8-bd91-3bb4fb5db1e4");
};
```

**Comment by kum-deepak** [comment]
You might try [onWebSocketClose](https://stomp-js.github.io/api-docs/latest/classes/Client.html#onWebSocketClose), it receives [CloseEvent](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent). The underlying system is supposed to provide the cause through CloseEvent.
