### ISSUE TITLE
RxStompService. If I unsubscribe from one topic, I do not get data on other topics

### ISSUE THREAD

**Issue by ezhuikova** [stomp-js/rx-stomp#8]
Hi!
I use RxStompService

If i run updateSubscriptions the second time, i get data only for topic2.
```
updateSubscriptions() {
    if (this.topicSubscription1 != null) {
      this.topicSubscription1.unsubscribe();
    }
    this.topicSubscription1 = this.rxStompService.watch('/topic/topic1').subscribe((message: Message) => {
      this.receivedMessages.push(message.body);
    });

    setTimeout(() => {
      if (this.topicSubscription2 != null) {
        this.topicSubscription2.unsubscribe();

        this.topicSubscription2 = this.rxStompService.watch('/topic/topic2').subscribe((message: Message) => {
          this.receivedMessages.push(message.body);
        });
      }
    }, 1500);

  }
```

I think it this.topicSubscription2.unsubscribe(); call  unsubscribe for **all** subscriptions

>>> SUBSCRIBE
ack:auto
id:sub-0
destination:/topic/topic1

>>> SUBSCRIBE
ack:auto
id:sub-1
destination:/topic/topic2

>>> UNSUBSCRIBE
id:sub-0

Request to subscribe /topic/topic1

>>> SUBSCRIBE
ack:auto
id:sub-2
destination:/topic/topic1

>>> UNSUBSCRIBE
id:sub-1

Request to subscribe /topic/topic2

>>> SUBSCRIBE
ack:auto
id:sub-3
destination:/topic/topic2

**Comment by ramakanthreddyk** [comment]
is there a way to unwatch

**Comment by kum-deepak** [comment]
In is handled as per RxJS. If you are subscribing like below, save the return value and later call unsubscribe on that.

```typescript
this.topicSubscription = this.rxStompService.watch('/topic/topic1').subscribe((message: Message) => {
      // Do something
});

// When you want to unwatch
this.topicSubscription.unsubscribe();
```
